Remove throwing/originating errors in expected scenarios (Lookup/TryLookup and Cancel) (#1512)
* non-originating error compiles

* fix with test cases

* and remove ignore

* add runsettings to run tests from visual studio tester, modified readme, make shouldOrigiante a template param.

* change map shouldOriginate to template parameter. Note, could be a breakig change for usages of map that are not default (i.e. custom std::less)
if so, might need to split up templates into separate template, or spin out into separate pr.

changed bool to template parameter in hresult_error, as the char*-to-bool decaying conversion failed the old tests.

also fixed runsettings, added note in readme.

* settle on avoid_originate as naming scheme

* add a printf only to Lookup so we can add SFINAE or something like that.

* weird templating magic required... still not working, has error
1>G:\source\repos\cppwinrt\_build\x64\Debug\winrt\Windows.Foundation.Collections.h(868,51): error C3878: syntax error: unexpected token '>' following 'simple-type-specifier'
1>(compiling source file '/Class.cpp')
1>    G:\source\repos\cppwinrt\_build\x64\Debug\winrt\Windows.Foundation.Collections.h(868,51):
1>    missing one of: '(' '{' ?

* trylookup exists to avoid throwing an error, and let's avoid avoid_originate now.

* remove test.

* cleaned up and correctness.

* undo changes to untouched files

* spacing changes , change do declval.

* added special tag to parameter list to make sure not to break existing TryLookup impls, added test to verify this.

* address avoid_oritinate comment, no need for a different name, resuse existing hresult_cancelled

* change out async to a new name, with it being true by default.
add new unittest to test nullable lookup.

* Address hresult comments by adding tests and removing source_locatoin, special-cased further by checking the typename.

* add unittest without specialization, make sure that the behaviour is opt-in

---------

Co-authored-by: Chris Guzak <chris_guzak@msn.com>